theme: jekyll-theme-cayman
title: Valuable Trash
email: valuabletrashproject@gmail.com
favicon: https://user-images.githubusercontent.com/83014418/153567941-3c92b033-b827-4dab-b9b1-3b232acc6b74.png
description: Valuable Trash is an intuitive and innovative app that uses AI to help you repurpose your waste. It enables you to practically and creatively reduce your carbon footprint.
uistring:
    title: Valuable Trash # title to appear in nav bar and page meta
    description: Valuable Trash is an intuitive and innovative app that uses AI to help you repurpose your waste. It enables you to practically and creatively reduce your carbon footprint. # Displays as site description meta tag for site
    copyright: 2022 Valuable Trash # appears in footer
